### ISSUE TITLE
Adding re3data to the list?

### ISSUE THREAD

**Issue by poikilotherm** [NLeSC/awesome-research-software-registries#25]
Looking at https://www.re3data.org/search?query=&contentTypes%5B%5D=Source%20code, you can find a lot of research data repositories accepting source code, too.

No idea if this is beyond scope for this AWESOME list :wink: 

No one is yet using CodeMeta or CFF standards, so this is not available as filter. Support is rising for it, like it is in Dataverse (see IQSS/dataverse#2739 and IQSS/dataverse#6289)

**Comment by jspaaks** [comment]
Great find, thanks!
